version: '3'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis:alpine
volumes: 
  db_data: 

